//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public int LibraryId { get; set; }
        public string LibraryItemName { get; set; }
        public string LibraryItemUrl { get; set; }
        public bool LibraryItemType { get; set; }
    }
}
