//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.AssignTasks = new HashSet<AssignTask>();
            this.Transcripts = new HashSet<Transcript>();
        }
    
        public int TaskId { get; set; }
        public string TaskName { get; set; }
        public string TaskUrl { get; set; }
        public string TaskStartDate { get; set; }
        public int TaskDuration { get; set; }
        public string TaskDetails { get; set; }
        public int TaskCategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignTask> AssignTasks { get; set; }
        public virtual TaskCategory TaskCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transcript> Transcripts { get; set; }
    }
}
